{% set name = "Orange3-Recommendation" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Orange3-Recommendation-{{ version }}.tar.gz
  sha256: 8506f4db4321a90023edf429315be730fadbc1660ae6e461a81c7cb58e3f3f4e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >3
    - pip
  run:
    - python  >3
    - orange3
    - mock
    - numpy >=1.9.0
    - scikit-learn >=0.17
    - setuptools-git

test:
  imports:
    - orangecontrib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/biolab/orange3-recommendation
  summary: Orange3 add-on for recommender systems
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - HeavyTonty2
