{% set name = "orange3-prototypes" %}
{% set version = "0.21.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Orange3-Prototypes-{{ version }}.tar.gz
  sha256: 552b78f7ab112dfe42c05231d54591e5ff4e76746e14a82ad670681744294a1d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - orange3 >=3.34
    - numpy >=1.19.5
    - scipy >=1.9.0
    - scikit-learn >=1.0.1
    - pyqtgraph
    - anyqt >=0.1.0
    - pandas >=1.3.0
    - openai >=1
    - tiktoken

test:
  imports:
    - orangecontrib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/biolab/orange3-prototypes
  summary: Prototype Orange widgets — only for the brave.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HeavyTony2
