{% set name = "wptools" %}
{% set version = "0.4.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wptools-{{ version }}.tar.gz
  sha256: 6f77eda0f19cdd0e3e31c6759fd18baa1fef1357668e9838f3d2380451b83e26

build:
  entry_points:
    - wptool=scripts.wptool:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv
  number: 0

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - certifi
    - html2text
    - lxml
    - pycurl
test:
  imports:
    - scripts
    - wptools
  commands:
    - pip check
    - wptool --help
  requires:
    - pip

about:
  home: https://github.com/siznax/wptools/
  dev_url: https://github.com/siznax/wptools/
  doc_url: https://github.com/siznax/wptools/wiki
  summary: Wikipedia tools (for Humans)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HeavyTony2
