{% set name = "wikidata-dl" %}
{% set version = "2023.7.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wikidata_dl-{{ version }}.tar.gz
  sha256: b8484c5e64696fa49e43ed56dfdf6d188c2b6336ea3a5291f589674d42e41fdc

build:
  entry_points:
    - wikidata-dl = wikidata_dl.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - httpx
    - python-dateutil
    - wptools

test:
  imports:
    - wikidata_dl
  commands:
    - pip check
    - wikidata-dl --help
  requires:
    - pip

about:
  summary: Download data from Wikidata based on input SPARQL query.
  dev_url: https://github.com/yaph/wikidata-dl
  license: MIT
  home: https://github.com/yaph/wikidata-dl
  license_file: LICENSE
  description: |
    *wikidata-dl* is a command line program for downloading data from *Wikidata* based on *SPARQL* queries.

extra:
  recipe-maintainers:
    - HeavyTony2
