{% set name = "wikiart" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lucasdavid/wikiart/archive/v{{ version }}.tar.gz
  sha256: 2abf2dc4a952380897df77637dd3c45dc34e3b7cc5cfb33930248035387858b1

build:
  entry_points:
    - wikiart = wikiart.console:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - python
    - requests

test:
  imports:
    - wikiart
  commands:
    - pip check
    - wikiart --help
  requires:
    - pip

about:
  home: https://github.com/lucasdavid/wikiart-retriever
  license: MIT
  license_file: LICENSE
  summary: Full retriever for art and metadata in http://wikiart.org/.
extra:
  recipe-maintainers:
    - HeavyTony2
