{% set name = "aphrodite-flash-attn" %}
{% set version = "2.6.1.post2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AlpinDale/flash-attention/archive/v{{ version }}.tar.gz
  sha256: 081ff239ec3008c2b9d298795fa76de57025beabbdf9dd092f9ffa7f463ae318

build:
  skip: true  # [not linux]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
  host:
    - python
    - psutil
    - pip
    - pytorch ==2.4.0
  run:
    - python
    - pytorch ==2.4.0
    - cuda-version {{ cuda_compiler_version }}


test:
  imports:
    - aphrodite_flash_attn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AlpinDale/flash-attention.git
  summary: Cross-platform lib for process and system monitoring in Python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HeavyTony2
