{% set name = "audioop-lts" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/audioop_lts-{{ version }}.tar.gz
  sha256: e81268da0baa880431b68b1308ab7257eb33f356e57a5f9b1f915dfb13dd1387

build:
  skip: true  # [py<313]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - audioop
  commands:
    - pip check
  requires:
    - pip

about:
  summary: LTS Port of Python audioop
  license: EPL-2.0
  license_file: LICENSE
  description: An LTS port of the Python builtin module `audioop` which was deprecated since version 3.11 and removed in 3.13.
  home: https://github.com/AbstractUmbra/audioop

extra:
  recipe-maintainers:
    - HeavyTony2
